on: workflow_dispatch
jobs:
  az:
    runs-on: ubuntu-26.04-arm
    steps:
      - run: |
          git clone https://github.com/nejason57mars/mcbot.git
          cd mcbot
          java -jar MCBOT.jar 46.174.53.38:25565 776 botjoiner 150 100
