on: workflow_dispatch
jobs:
  zhalost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          RUSTFLAGS="-C target-cpu=native" cargo build --release
          ./my_app 46.174.53.38 25565 300
